baseURL = "http://example.org/"
languageCode = "en-us"
title = "Diana Lovette"
theme = "aafu"

[params]
    title = "DL"
    author = "Diana Lovette"
    description = "Summary of Diana Lovette"
    copyright = "Hey There"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Diana Lovette"
		tagline = "Web Developer"
		location = "San Francisco Bay Area, CA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/dianalovette/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/birbjam"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa fa-envelope"
            url = "mailto:dianalovette90@gmail.com"
            title = "Email"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Hi! I'm a fledgling full stack web developer of about a year's worth of experience with an emphasis on JavaScript, Node, and React. I create websites and applications. I started teaching myself to code in September of 2018 and completed the Berkeley Extension Full Stack Web Development Bootcamp in August 2019. Since completing the bootcamp, I have been working part time as a web developer for UC Berkeley's Museum of Vertebrate Zoology."

    # Note to self: links: Sent [emails](#).
    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Remote Web Developer"
            dates = "January 2019 - *Present*"
            company = "UC Berkeley, Museum of Vertebrate Zoology"
            details = "Designing and developing user interfaces using HTML/CSS with JavaScript and APIs to display biological data. Addressing issues in project repositories."
        [[params.experience.list]]
            position = "Intro to Web Development Volunteer Instructor"
            dates = "October 2019 - March 2020"
            link = "https://codenation.org/"
            company = "Code Nation"
            details = "Taught students web development basics through a preset curriculum. Provided feedback to students on projects they worked on. Supported other instructors during lessons by helping students with classwork and addressing questions."
        [[params.experience.list]]
            position = "Remote Front End Web Developer"
            dates = "July 2019 - September 2019"
            company = "Biocode LLC"
            details = "Designed and developed responsive websites using HTML/CSS with JavaScript and APIs. Communicated with clients to address issues and tailor websites to meet requirements. Troubleshot and tested code."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Degree In Progress"
            college = "Diablo Valley Community College"
            dates = "Starting in Summer 2020"
        [[params.education.list]]
            degree = "Full Stack Web Development Bootcamp, Certificate of Completion"
            college = "UC Berkeley Extension"
            dates = "February 2019 - August 2019"
        [[params.education.list]]
            degree = "Degree In Progress"
            college = "University of North Florida"
            dates = "2009 - 2011"

    
    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Amphibian Disease Portal"
            url = "https://github.com/BNHM/AmphibiaWebDiseasePortal"
            description = "A complete rework of the user interface of the original Amphibian Disease Portal using Hugo for static site generation and the GEOME API due to the project’s migration to a new database. When the project is complete, the user will be able to look up scientific data associated with the fungi that are affecting amphibian populations around the world."
        [[params.project.list]]
            title = "Species Lookup Service"
            url = "https://specieslookup.berkeley.edu/"
            description = "A species mapper using the Leaflet API connecting to a pre-built back-end species API. The user can click on any part of the map to find out what species of amphibians have been found in that region."
        [[params.project.list]]
            title = "Pusheen Memory Game"
            url = "https://pusheen-memory-game.herokuapp.com/"
            description = "A React game application where the user clicks on images and collects points based on the amount of unique images clicked. If an image is clicked on more than once, the game is over and the score restarts. The maximum score a user can get is 12, in which case the user wins the game."
        [[params.project.list]]
            title = "Learn Local"
            url = "https://learnlocal3.herokuapp.com/"
            description = "A website using the MERN stack created by myself, Hetty Chin, and Emily Liang, where a user can sign up to take or teach a class. Includes a dynamic map that moves to the location of the class if an address is provided."            
        [[params.project.list]]
            title = "LIRI Bot"
            url = "https://github.com/birbjam/liri-cli-app"
            description = "A command line Node application that takes in user parameters and gives back data from Spotify, OMDB, and Bands In Town"
    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "HTML / CSS"
            skillrating = 60
        [[params.skill.list]]
            skill = "Bootstrap"
            skillrating = 40
        [[params.skill.list]]
            skill = "JavaScript"
            skillrating = 50
        [[params.skill.list]]
            skill = "Node"
            skillrating = 40
        [[params.skill.list]]
            skill = "React"
            skillrating = 40
        [[params.skill.list]]
            skill = "Express"
            skillrating = 40
        [[params.skill.list]]
            skill = "MongoDB"
            skillrating = 40

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cold Process Soap Making"
        [[params.hobby.list]]		
		    hobby = "Farming and Gardening"
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Hiking and Running"